version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
  db:
    image: mysql:8.0
    container_name: genesis_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0 --explicit_defaults_for_timestamp
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - app-tier

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: genesis_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: password
    ports:
      - 8080:80
    networks:
      - app-tier
