version: "3.8"

services:
  mysql_master:
    image: mysql:latest
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classicmodels
    ports:
      - "3306:3306"
    volumes:
      - master_data:/var/lib/mysql
      - ./master/my.cnf:/etc/mysql/my.cnf
      - ./master/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./master/replica_user_setup.sql:/docker-entrypoint-initdb.d/replica_user_setup.sql

  mysql_slave:
    image: mysql:latest
    container_name: mysql_slave
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - slave_data:/var/lib/mysql
      - ./slave/my.cnf:/etc/mysql/my.cnf
      - ./slave/init-slave.sh:/docker-entrypoint-initdb.d/init-slave.sh
    ports:
      - "3307:3306"
    depends_on:
      - mysql_master
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql_master
    environment:
      PMA_HOST: mysql_master
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  master_data:
  slave_data:
